# -*- coding: utf-8 -*-
"""GRUs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aAREcZNJis9ISB79HhYAzVV3iFFZZUB8
"""

!pip install opendatasets

import opendatasets as od

od.download("https://www.kaggle.com/datasets/shivendratomar/grus-dataset")

import pandas as pd
final_df = pd.read_csv("/content/grus-dataset/Final_Cleaned_Dataset_with_sorting.csv")

import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.preprocessing.sequence import pad_sequences

print("⚙️ Initiating GRU Data Transformation Pipeline...")

# -------------------------------------------------------------------
# STEP 1: TIME SORTING & TARGET CREATION
# -------------------------------------------------------------------
# Make sure event_time is a proper datetime object
final_df['event_time'] = pd.to_datetime(final_df['event_time'])

# Sort by session and then strictly by time (The "Movie" must be in order)
seq_df = final_df.sort_values(by=['user_session', 'event_time']).copy()

# Find which sessions actually resulted in a purchase (Our Target 'y')
# Hum ek dictionary bana rahe hain: {session_id: 1 ya 0}
session_targets = seq_df.groupby('user_session')['event_type'].apply(
    lambda events: 1 if 'purchase' in events.values else 0
).to_dict()


# -------------------------------------------------------------------
# STEP 2: PREVENTING "DATA LEAKAGE" (Cheating)
# -------------------------------------------------------------------
# WARNING: Hum GRU ke input mein 'purchase' event nahi bhej sakte.
# Agar model ne input mein hi 'purchase' dekh liya, toh wo cheat karke output 1 de dega.
# Isliye hum sirf 'view' aur 'cart' events ko as a sequence use karenge.
seq_df = seq_df[seq_df['event_type'] != 'purchase'].copy()


# -------------------------------------------------------------------
# STEP 3: FEATURE ENGINEERING FOR SEQUENCE
# -------------------------------------------------------------------
# 1. Encoding Event Types (Neural Nets string nahi samajhte)
seq_df['is_view'] = (seq_df['event_type'] == 'view').astype(int)
seq_df['is_cart'] = (seq_df['event_type'] == 'cart').astype(int)

# 2. Extracting "Time Gap" (Hesitation Time between clicks)
seq_df['time_gap_seconds'] = seq_df.groupby('user_session')['event_time'].diff().dt.total_seconds().fillna(0)

# Time gaps bohot extreme ho sakte hain (e.g., 0 sec to 5000 sec).
# Deep learning extreme numbers se confuse hota hai, isliye hum ispe Log transform lagayenge.
seq_df['log_time_gap'] = np.log1p(seq_df['time_gap_seconds'])

# 3. Scaling Price (0 to 1 ke beech lana zaroori hai weights stable rakhne ke liye)
scaler = MinMaxScaler()
seq_df['scaled_price'] = scaler.fit_transform(seq_df[['price']])


# -------------------------------------------------------------------
# STEP 4: BUILDING THE 3D ARRAY (The Magic Step)
# -------------------------------------------------------------------
# Jo 4 features hum GRU ko sikhana chahte hain:
sequence_features = ['is_view', 'is_cart', 'scaled_price', 'log_time_gap']

print("Grouping events into sequential lists...")
# Har session ka data ab ek 2D list ban jayega
session_groups = seq_df.groupby('user_session')[sequence_features].apply(lambda x: x.values.tolist())

# Aligning Targets (y) with the sequences
y = np.array([session_targets[session_id] for session_id in session_groups.index])

# -------------------------------------------------------------------
# STEP 5: PADDING TO FIXED LENGTH
# -------------------------------------------------------------------
# GRU matrix ki shape hamesha fix honi chahiye. Hum aakhri 15 actions par focus karenge.
MAX_STEPS = 15

print(f"Padding/Truncating sequences to {MAX_STEPS} steps...")
# padding='pre': Agar 15 se kam events hain, toh shuru mein [0,0,0,0] lag jayega.
# truncating='pre': Agar 50 events hain, toh purane 35 bhool jayega, sirf aakhri 15 yaad rakhega.
X = pad_sequences(session_groups.tolist(), maxlen=MAX_STEPS, padding='pre', truncating='pre', dtype='float32')

print("-" * 50)
print("✅ SUCCESS! Data is ready for GRU.")
print(f"🔹 Shape of Input (X): {X.shape}  --> (Total Sessions, Time Steps, Features)")
print(f"🔹 Shape of Target (y): {y.shape}    --> (Total Sessions,)")

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import GRU, Dense, Dropout, Masking
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.model_selection import train_test_split

print("🧠 Building the GRU Neural Network...")
X = np.asarray(X).astype(np.float32)
y = np.asarray(y).astype(np.float32)

# FIX 2: The Magic Line (Kill all NaNs and Infinities)
# Agar pichle step mein koi NaN ya Infinity ban gaya tha, ye usko safely 0.0 bana dega
X = np.nan_to_num(X, nan=0.0, posinf=0.0, neginf=0.0)

print(f"Data Sanity Check (Should be 0): {np.isnan(X).sum()} NaNs found.")

# STEP 1: Train-Test Split (Sequence data ko split karna)
# X shape: (Total_Sessions, 15, 4)
# y shape: (Total_Sessions,)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# STEP 2: Model Architecture Define Karna
model = Sequential()

# Layer 0: Explicit Input Layer (Recommended Keras practice to avoid warning)
model.add(tf.keras.Input(shape=(X.shape[1], X.shape[2])))

# Layer 1: The Masking Layer (Sabse Zaroori!)
# Humne padding mein jo '0' dale the, ye layer GRU ko bolegi ki unhe ignore karo.
model.add(Masking(mask_value=0.0))
# input_shape = (15 steps, 4 features) is now handled by the Input layer

# Layer 2: The GRU Brain
# 64 units ka matlab hai GRU ke paas 64 "neurons" ki memory capacity hai
model.add(GRU(units=64, return_sequences=False, activation='tanh'))

# Layer 3: Dropout (Overfitting rokne ke liye)
# Ye 20% neurons ko random time par band kar dega taaki model "ratta" na maare (memorize na kare)
model.add(Dropout(0.2))

# Layer 4: Dense (Processing Layer)
model.add(Dense(units=32, activation='relu'))

# Layer 5: Output Layer (The Final Decision)
# Sigmoid activation hamesha 0 se 1 ke beech ka probability score deta hai
model.add(Dense(units=1, activation='sigmoid'))


# STEP 3: Model Compile Karna
print("⚙️ Compiling the model...")
model.compile(
    optimizer='adam',
    loss='binary_crossentropy', # Kyunki answer sirf Yes (1) ya No (0) hai
    metrics=['accuracy', tf.keras.metrics.AUC(name='auc')] # AUC recall/precision balance ke liye best hai
)

model.summary()

# STEP 4: Training (Fitting the model)
# EarlyStopping: Agar model seekhna band kar de, toh training khud rok do taaki time bache
early_stop = EarlyStopping(monitor='val_auc', mode='max', patience=3, restore_best_weights=True)

print("\n🚀 Starting Training...")
history = model.fit(
    X_train, y_train,
    epochs=15,          # Maximum 15 baar poora data dekhega
    batch_size=256,     # Ek baar mein 256 sessions process karega (speed ke liye)
    validation_split=0.2,
    callbacks=[early_stop]
)

# STEP 5: Final Testing
print("\n📊 Evaluating on Test Data...")
test_loss, test_acc, test_auc = model.evaluate(X_test, y_test)
print(f"Test Accuracy: {test_acc:.4f}")
print(f"Test AUC Score: {test_auc:.4f}")

import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import GRU, Dense, Dropout, Masking
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.model_selection import train_test_split

print("⚙️ Initiating GRU Data Transformation Pipeline (Colab GPU Optimized)...")

# --- DATA PREPARATION PHASE ---

# 1. Sort by session and time
final_df['event_time'] = pd.to_datetime(final_df['event_time'])
seq_df = final_df.sort_values(by=['user_session', 'event_time']).copy()

# 2. Target Creation (1 if purchased, else 0)
session_targets = seq_df.groupby('user_session')['event_type'].apply(
    lambda events: 1 if 'purchase' in events.values else 0
).to_dict()

# 3. Remove 'purchase' events from input sequence to prevent cheating
seq_df = seq_df[seq_df['event_type'] != 'purchase'].copy()

# 4. Feature Engineering
seq_df['is_view'] = (seq_df['event_type'] == 'view').astype(int)
seq_df['is_cart'] = (seq_df['event_type'] == 'cart').astype(int)
seq_df['time_gap_seconds'] = seq_df.groupby('user_session')['event_time'].diff().dt.total_seconds().fillna(0)
seq_df['log_time_gap'] = np.log1p(seq_df['time_gap_seconds'])

scaler = MinMaxScaler()
seq_df['log_price'] = np.log1p(seq_df['price'])
scaler = MinMaxScaler()
seq_df['scaled_price'] = scaler.fit_transform(seq_df[['log_price']])

sequence_features = ['is_view', 'is_cart', 'scaled_price', 'log_time_gap']

print("Grouping events into sequential lists...")
session_groups = seq_df.groupby('user_session')[sequence_features].apply(lambda x: x.values.tolist())
y = np.array([session_targets[session_id] for session_id in session_groups.index])

# 5. SEQUENCE PADDING (THE FIX FOR CUDNN)
MAX_STEPS = 15
print(f"Padding sequences to {MAX_STEPS} steps (Using 'post' padding for cuDNN)...")
# Changed padding from 'pre' to 'post'
X = pad_sequences(session_groups.tolist(), maxlen=MAX_STEPS, padding='post', truncating='pre', dtype='float32')

# 6. DATA SANITIZATION (Safeguard against NaNs)
print("🧹 Sanitizing Data...")
X = np.asarray(X).astype(np.float32)
y = np.asarray(y).astype(np.float32)
X = np.nan_to_num(X, nan=0.0, posinf=0.0, neginf=0.0)

print(f"🔹 Final Shape of Input (X): {X.shape}")
print(f"🔹 Final Shape of Target (y): {y.shape}")
print("-" * 50)


# --- MODEL BUILDING & TRAINING PHASE ---

print("🧠 Building the GRU Neural Network...")

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

model = Sequential()

# Layer 0: Explicit Input Layer
model.add(tf.keras.Input(shape=(X.shape[1], X.shape[2])))

# Layer 1: Masking Layer
model.add(Masking(mask_value=0.0))

# Layer 2: GRU Layer (Will now safely use cuDNN)
model.add(GRU(units=64, return_sequences=False, activation='tanh'))

# Layer 3: Dropout
model.add(Dropout(0.2))

# Layer 4: Dense
model.add(Dense(units=32, activation='relu'))

# Layer 5: Output
model.add(Dense(units=1, activation='sigmoid'))

print("⚙️ Compiling the model...")
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy', tf.keras.metrics.AUC(name='auc')]
)

early_stop = EarlyStopping(monitor='val_auc', mode='max', patience=3, restore_best_weights=True)

print("\n🚀 Starting Training...")
history = model.fit(
    X_train, y_train,
    epochs=10,
    batch_size=256,
    validation_split=0.2,
    callbacks=[early_stop]
)

print("\n📊 Evaluating on Test Data...")
test_loss, test_acc, test_auc = model.evaluate(X_test, y_test)
print(f"Test Accuracy: {test_acc:.4f}")
print(f"Test AUC Score: {test_auc:.4f}")
import matplotlib.pyplot as plt

print("\n📈 Plotting Training History...")

# Ek badi figure banate hain jisme 3 alag-alag graphs aayenge (1 row, 3 columns)
plt.figure(figsize=(18, 5))

# ---------------------------------------------------------
# GRAPH 1: LOSS CURVE (Ye hamesha neeche jaana chahiye)
# ---------------------------------------------------------
plt.subplot(1, 3, 1)
plt.plot(history.history['loss'], label='Training Loss', color='blue', linewidth=2)
plt.plot(history.history['val_loss'], label='Validation Loss', color='red', linestyle='dashed', linewidth=2)
plt.title('Model Loss (Error) Over Epochs', fontsize=14, fontweight='bold')
plt.xlabel('Epochs', fontsize=12)
plt.ylabel('Loss (Binary Crossentropy)', fontsize=12)
plt.legend(loc='upper right')
plt.grid(True, linestyle='--', alpha=0.6)

# ---------------------------------------------------------
# GRAPH 2: ACCURACY CURVE (Ye hamesha upar jaana chahiye)
# ---------------------------------------------------------
plt.subplot(1, 3, 2)
plt.plot(history.history['accuracy'], label='Training Accuracy', color='green', linewidth=2)
plt.plot(history.history['val_accuracy'], label='Validation Accuracy', color='orange', linestyle='dashed', linewidth=2)
plt.title('Model Accuracy Over Epochs', fontsize=14, fontweight='bold')
plt.xlabel('Epochs', fontsize=12)
plt.ylabel('Accuracy Score', fontsize=12)
plt.legend(loc='lower right')
plt.grid(True, linestyle='--', alpha=0.6)

# ---------------------------------------------------------
# GRAPH 3: AUC CURVE (E-commerce ke liye sabse important)
# ---------------------------------------------------------
# Dhyan dein: Keras history dict mein AUC ki key kabhi 'auc' hoti hai,
# kabhi 'auc_1' wagera. Hum directly exact name fetch kar lenge:
auc_key = [k for k in history.history.keys() if 'auc' in k and 'val' not in k][0]
val_auc_key = 'val_' + auc_key

plt.subplot(1, 3, 3)
plt.plot(history.history[auc_key], label='Training AUC', color='purple', linewidth=2)
plt.plot(history.history[val_auc_key], label='Validation AUC', color='magenta', linestyle='dashed', linewidth=2)
plt.title('Model AUC Score Over Epochs', fontsize=14, fontweight='bold')
plt.xlabel('Epochs', fontsize=12)
plt.ylabel('AUC Score', fontsize=12)
plt.legend(loc='lower right')
plt.grid(True, linestyle='--', alpha=0.6)

# Layout ko thoda saaf karke display karna
plt.tight_layout()
plt.show()

"""### Testing the data:-"""

import numpy as np
from tensorflow.keras.preprocessing.sequence import pad_sequences

print("🧪 RUNNING GRU PSYCHOLOGY TEST CASES...\n")

# Helper function time gap ko log mein badalne ke liye
def time_to_log(seconds):
    return np.log1p(seconds)

# Features ka order: [is_view, is_cart, scaled_price, log_time_gap]
# Note: Price ko hum seedha 0.0 (Cheap) se 1.0 (Expensive) ke beech likh rahe hain

# -----------------------------------------------------------------------------
# TEST CASE 1: "The VIP Focused Buyer"
# Behavior: Mehenga item dekha, turant cart mein dala (Low hesitation).
# Expectation: Very High Probability (> 0.80)
# -----------------------------------------------------------------------------
buyer_vip = [
    [1, 0, 0.9, time_to_log(0)],   # Step 1: View phone
    [1, 0, 0.9, time_to_log(15)],  # Step 2: View same phone again after 15 secs
    [0, 1, 0.9, time_to_log(10)]# Step 3: Add to cart after 10 secs
]

# -----------------------------------------------------------------------------
# TEST CASE 2: "The Window Shopper (Timepass)"
# Behavior: Sasti cheezein dekh raha hai, bohot lamba time le raha hai, no cart.
# Expectation: Very Low Probability (< 0.20)
# -----------------------------------------------------------------------------
buyer_window = [
    [1, 0, 0.1, time_to_log(0)],    # Step 1: View cheap case
    [1, 0, 0.2, time_to_log(120)],  # Step 2: View another case (2 mins later)
    [1, 0, 0.1, time_to_log(300)],  # Step 3: View again (5 mins later)
    [1, 0, 0.3, time_to_log(400)]   # Step 4: View again (6.5 mins later)
]

# -----------------------------------------------------------------------------
# TEST CASE 3: "The Cart Abandoner (Drop-off Risk)"
# Behavior: Cart mein dala, par uske baad achanak bohot bada time gap aa gaya (Fas gaya).
# Expectation: Moderate to Low Probability (GRU should catch the hesitation!)
# -----------------------------------------------------------------------------
buyer_abandoner = [
    [1, 0, 0.5, time_to_log(0)],    # Step 1: View Mid-range item
    [0, 1, 0.5, time_to_log(30)],   # Step 2: Add to cart (Good sign!)
    [1, 0, 0.5, time_to_log(1800)]  # Step 3: View homepage again after 30 MINUTES (Bad sign!)
]

# --- PREPARING DATA FOR MODEL ---
MAX_STEPS = 15

# Pad the sequences (Must use 'post' padding to match training data)
test_sequences = [buyer_vip, buyer_window, buyer_abandoner]
X_test_cases = pad_sequences(test_sequences, maxlen=MAX_STEPS, padding='post', dtype='float32')

# Get Predictions
predictions = model.predict(X_test_cases, verbose=0)

# --- PRINTING RESULTS ---
print("📊 TEST RESULTS:")
print("-" * 50)
print(f"1. VIP Focused Buyer  : {predictions[0][0]*100:.2f}% Chance of Purchase")
print(f"2. Window Shopper     : {predictions[1][0]*100:.2f}% Chance of Purchase")
print(f"3. Cart Abandoner     : {predictions[2][0]*100:.2f}% Chance of Purchase")
print("-" * 50)

model.save_weights('gru_model_weights.weights.h5')
print("Model weights saved to 'gru_model_weights.weights.h5'")

from google.colab import drive
drive.mount('/content/drive')